import {
  Add,
  Subtract,
  Multiply,
  Divide,
  Square,
  Cube,
  SquareRoot,
  CubeRoot,
  NthRoot,
  Percent,
  Negate,
  Power,
  TenPower,
  DivideByN,
  Factorial,
  Random,
  MemoryAdd,
  MemoryClear,
  MemoryRecall,
  MemorySubtract,
} from '../calculator/calculator';

export const buttons = [
  { icon: '(', value: '(', type: 'complex' },
  { icon: ')', value: ')', type: 'complex' },
  { icon: 'mc', operation: () => new MemoryClear(), type: 'complex' },
  { icon: 'm+', operation: () => new MemoryAdd(), type: 'complex' },
  { icon: 'm-', operation: () => new MemorySubtract(), type: 'complex' },
  { icon: 'mr', operation: () => new MemoryRecall(), type: 'complex' },

  { icon: '2nd', type: 'complex' },
  { icon: 'x²', operation: () => new Square(), type: 'complex' },
  { icon: 'x³', operation: () => new Cube(), type: 'complex' },
  { icon: 'xʸ', operation: (value) => new Power(value), type: 'complex' },
  { icon: 'eˣ', type: 'complex' },
  { icon: '10ˣ', operation: () => new TenPower(), type: 'complex' },

  { icon: '1/x', operation: () => new DivideByN(), type: 'complex' },
  { icon: '²√x', operation: () => new SquareRoot(), type: 'complex' },
  { icon: '³√x', operation: () => new CubeRoot(), type: 'complex' },
  { icon: 'ʸ√x', operation: (value) => new NthRoot(value), type: 'complex' },
  { icon: 'ln', type: 'complex' },
  { icon: 'log₁₀', type: 'complex' },

  { icon: 'x!', operation: () => new Factorial(), type: 'complex' },
  { icon: 'sin', type: 'complex' },
  { icon: 'cos', type: 'complex' },
  { icon: 'tan', type: 'complex' },
  { icon: 'e', value: 2.7183, type: 'complex' },
  { icon: 'EE', type: 'complex' },

  { icon: 'Rad', type: 'complex' },
  { icon: 'sinh', type: 'complex' },
  { icon: 'cosh', type: 'complex' },
  { icon: 'tanh', type: 'complex' },
  { icon: 'π', value: 3.141592653589793, type: 'complex' },
  { icon: 'Rand', operation: () => new Random(), type: 'complex' },

  { icon: 'AC', operation: 'clear', type: 'basic' },
  { icon: '+/-', operation: () => new Negate(), type: 'basic' },
  { icon: '%', operation: () => new Percent(), type: 'basic' },
  { icon: '÷', operation: (value) => new Divide(value), type: 'basic' },
  { icon: '7', value: '7', type: 'basic' },
  { icon: '8', value: '8', type: 'basic' },
  { icon: '9', value: '9', type: 'basic' },
  { icon: '×', operation: (value) => new Multiply(value), type: 'basic' },
  { icon: '4', value: '4', type: 'basic' },
  { icon: '5', value: '5', type: 'basic' },
  { icon: '6', value: '6', type: 'basic' },
  { icon: '-', operation: (value) => new Subtract(value), type: 'basic' },
  { icon: '1', value: '1', type: 'basic' },
  { icon: '2', value: '2', type: 'basic' },
  { icon: '3', value: '3', type: 'basic' },
  { icon: '+', operation: (value) => new Add(value), type: 'basic' },
  { icon: '0', value: '0', type: 'basic' },
  { icon: '.', value: '.', type: 'basic' },
  { icon: '=', operation: 'equal', type: 'basic' },
];
